### ISSUE TITLE
Wrong calculation! 

### ISSUE THREAD

**Issue by DataEnggNerd** [Zeutschler/nanocube#7]
For comparing the performance between polars and nanocube, I have wrote a test and the results seems to be wrong. I am not able to correlate the actual result with the expected result as well. 

My code 
```py
from pandas import read_csv as pd_read_csv
from nanocube import NanoCube
from polars import read_csv, col

def filter_with_polars():
    df = read_csv("spotify_data.csv")
    result = df.filter(col("daily") == 1337404).select("streams").sum()
    print(result)
    # shape: (1, 1)
    # ┌────────────┐
    # │ streams    │
    # │ ---        │
    # │ i64        │
    # ╞════════════╡
    # │ 3518744128 │
    # └────────────┘

def filter_with_nanocube():
    df = pd_read_csv("spotify_data.csv")
    nc = NanoCube(df)
    result = nc.get("streams", daily=1337404)
    print(result)
    # 2345359210015

if __name__ == "__main__":
    filter_with_polars()
    filter_with_nanocube()
    # main()
```

I have added the results in respective methods.
Data - https://www.kaggle.com/datasets/asmonline/spotify-song-performance-dataset
 Am I missing something here?

**Comment by Zeutschler** [comment]
many thanks!, I'll check it.

**Comment by Zeutschler** [comment]
It's a feature not a bug. The problem is that NanoCube interprets 'Daily' as a measure column, because it's numerical, as is can not resolve 'Daily' as dimension it thinks that you want have the total over all columns and returns it.

If you would define `nc = NanoCube(df, dimensions=['Daily'], measures=['Streams'])` it works as desired.

So, not a bug, but a lack of documentation.

**Comment by Zeutschler** [comment]
Not a bug, it's. a feature.

**Comment by Zeutschler** [comment]
Just so everyone can see it...

**Comment by DataEnggNerd** [comment]
I can create a PR for adding this into documentation.
